CREATE TABLE Employee
(
	Id INT PRIMARY KEY NOT NULL,
	AddressId INT NOT NULL
	FOREIGN KEY (AddressId) REFERENCES Address (Id),
	PersonId INT NOT NULL
	FOREIGN KEY (PersonId) REFERENCES Person (Id),
	CompanyName NVARCHAR(20) NOT NULL,
	Position NVARCHAR(30) NULL,
	EmployeeName NVARCHAR(100) NULL
);
