CREATE TABLE Employee
(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	AddressId INT NOT NULL,
	PersonId INT NOT NULL,
	CompanyName NVARCHAR(20) NOT NULL,
	Position NVARCHAR(30) NULL,
	EmployeeName NVARCHAR(100) NULL
);
